### ISSUE TITLE
es6 rewrite

### ISSUE THREAD

**Issue by zrisher** [mathphreak/node-steamcmd#11]
IMO `index.js` could be significantly cleaner and simpler if we could rely on es6 features. `test.js` is already reliant on async/await, but introducing such syntax into `index.js` [would break our compatability with node < 6.4](http://node.green/). Package.json declares this project is valid for ` "node": ">=4.7.0"`. 

@mathphreak How do you feel about updating that?

**Comment by zrisher** [comment]
Some color here on the LTS status of various node versions: 
https://github.com/nodejs/LTS

**Comment by mathphreak** [comment]
I definitely agree that `async`/`await` would make things much cleaner.

I think "don't break the latest LTS release" is a good principle, and now that Node.js v6.x is in LTS it's probably fine to break v4.x.

**Comment by mathphreak** [comment]
Actually, it looks like [async/await didn't land until Node.js v7.6](http://node.green/#ES2017-features-async-functions). Breaking v6.x is probably a bad idea. (Also, strictly speaking, async/await isn't ES6 but rather ES2017.)

**Comment by zrisher** [comment]
Agh, that's too bad. Perhaps we can do this in a year when v6 leaves LTS?

**Comment by mathphreak** [comment]
Probably.

**Comment by zrisher** [comment]
What about adding some `es6` that's v6 and not v7? Like `let`, `const`, arrow functions, etc?

**Comment by zrisher** [comment]
And native promises?
