### ISSUE TITLE
babel-preset-es2015-node is deprecated

### ISSUE THREAD

**Issue by zrisher** [mathphreak/node-steamcmd#5]
When installing the npm package for local development, I receive a warning that [`babel-preset-es2015-node`](https://github.com/rtsao/babel-preset-es2015-node) is deprecated and [`babel-preset-env`](https://github.com/babel/babel-preset-env) is preferred. It looks like a relatively simple transition, but I don't know much about babel yet, nor how I might need to configure this for the various supported platforms.

**Comment by mathphreak** [comment]
It looks like this is an outdated `ava` dependency. Fixed in 84d3061.
